# Generated by Django 4.1 on 2023-01-18 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='product_images/')),
                ('building_name', models.CharField(max_length=100)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('subcribers', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='user_images')),
                ('account_type', models.CharField(choices=[('BUSSINESS', 'BUSSINESS'), ('PERSONAL', 'PERSONAL')], default='PERSONAL', max_length=50)),
                ('contact_number', models.IntegerField(default=None)),
                ('passion', models.CharField(default=None, max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('subscribers', models.IntegerField(default=0)),
                ('profile_dp', models.ImageField(default='', upload_to='')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getit_api.products')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getit_api.users')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getit_api.users'),
        ),
        migrations.CreateModel(
            name='HowToUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('show', models.CharField(choices=[(True, True), (False, False)], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getit_api.users')),
            ],
        ),
    ]
