# Generated by Django 4.1 on 2023-01-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getit_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowToUse',
            new_name='HowToUseDB',
        ),
        migrations.RenameField(
            model_name='howtousedb',
            old_name='user',
            new_name='username',
        ),
    ]
