# Generated by Django 4.1 on 2023-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getit_api', '0002_rename_howtouse_howtousedb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtousedb',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
