# Generated by Django 4.1 on 2023-01-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getit_api', '0003_alter_howtousedb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtousedb',
            name='show',
            field=models.CharField(choices=[(True, True), (False, False)], default=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('streaming_id', models.CharField(max_length=50)),
                ('live', models.CharField(choices=[(True, True), (False, False)], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getit_api.products')),
            ],
        ),
    ]
