# Generated by Django 4.1 on 2023-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getit_api', '0004_alter_howtousedb_show_live'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Live',
            new_name='LiveDB',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
